// <auto-generated />
namespace ecomiks1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class perfil2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(perfil2));
        
        string IMigrationMetadata.Id
        {
            get { return "201709242236207_perfil2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
